\chapter{Geography}

Honduras has three major topographical regions, including a vast interior plateau of hills and mountains that dominate the landscape; the Caribbean lowlands, and the Pacific lowlands- fringing the Gulf of Fonseca. 

\noindent The forested interior hills and the Sierra Madre Mountains are crisscrossed by a large series of rivers and wide, fertile valleys; fronted by sandy beaches, the Caribbean lowlands extend along its entire northern coastline, and there, in the northeast, the Mosquito Coast is a broad uninhabited stretch of thick jungle, lagoons and mangrove swamps; the Pacific lowlands surround the Gulf of Fonseca, and that land also becomes somewhat swampy near the coast. 

\noindent The country has numerous cays and islands in the Caribbean Sea, including Isla de la Bahia (Bay Islands), the tiny Cayos Cocinos (Hog Islands), and the remote Swan Islands. A few long-dormant volcanic islands stand in the Gulf of Fonseca, including Tigre and Zacate. 

\noindent Honduras\index{worldatlas}is water-rich; the most important rivers include the Aquan, Coco, Patuca, Sico and Ulua; Lake Yojoa is the only significant lake, and the Caratasca Lagoon in the northeast is the largest of many coastal lagoons. 